### ISSUE TITLE
To generate lag-energy spectrum

### ISSUE THREAD

**Issue by samuzalbarua** [wilkinsdr/pyLag#5]
I was going through the "pyLag '' to get the energy--lag spectrum. As demonstrated I gave the name of the lightcurves (for e.g. 0.3_1kev_en300-1000.lc). Then, I kept all lightcurves in the current working directory where I imported pylag (>>>import pylag). 

But, while I try to load lightcurves by typing  >>>mylclist = pylag.EnergyLCList(lcfiles='*.lc'), I get the following errors. Even If I do not keep any lightcurve in the current working directory, the same errors appear.

Please have a look at the issue and help me out soon.

>>> import pylag
>>> mylclist = pylag.EnergyLCList(lcfiles='*.lc')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/serb/software/reverberration/pylag/lightcurve.py", line 1487, in __init__
    self.enmin, self.enmax, self.lclist = self.find_light_curves(searchstr, lcfiles, **kwargs)
  File "/home/serb/software/reverberration/pylag/lightcurve.py", line 1538, in find_light_curves
    enlist = list(set([re.search('(en[0-9]+\-[0-9]+)', lc).group(0) for lc in lcfiles]))
  File "/home/serb/software/reverberration/pylag/lightcurve.py", line 1538, in <listcomp>
    enlist = list(set([re.search('(en[0-9]+\-[0-9]+)', lc).group(0) for lc in lcfiles]))
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by wilkinsdr** [comment]
Typically, the light curves in a single set of energies should have the same prefix (for example the observation ID). For example, if you had light curves in the 0.3-1 and 1-2keV bands, you would name them something like obs1_en300-1000.lc and obs1_en1000-2000.lc. Note 'obs1' is the same on both light curves. If that prefix is different, then they will not be interpreted as belonging to the same energy set. Please let me know if you continue to have problems.

**Comment by hjsreehari** [comment]
Hi, I am facing the same problem. Gave the filenames as suggested but still gets AttributeError: 'NoneType' object has no attribute 'group'.
The terminal output is given below

In [8]: ls
0851990101_tbin10_en1000-1500.lc  0851990101_tbin10_en7000-10000.lc  0851990201_tbin10_en5000-7000.lc
0851990101_tbin10_en1500-2000.lc  0851990101_tbin10_en800-1000.lc    0851990201_tbin10_en600-800.lc
0851990101_tbin10_en2000-3000.lc  0851990201_tbin10_en1000-1500.lc   0851990201_tbin10_en7000-10000.lc
0851990101_tbin10_en3000-5000.lc  0851990201_tbin10_en1500-2000.lc   0851990201_tbin10_en800-1000.lc
0851990101_tbin10_en300-400.lc    0851990201_tbin10_en2000-3000.lc   old/
0851990101_tbin10_en400-600.lc    0851990201_tbin10_en3000-5000.lc   Wilkins_2021_v0.py
0851990101_tbin10_en5000-7000.lc  0851990201_tbin10_en300-400.lc
0851990101_tbin10_en600-800.lc    0851990201_tbin10_en400-600.lc

In [9]: mylclist = pylag.EnergyLCList(lcfiles='*.lc')
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-9-92b97b11d83c> in <module>
----> 1 mylclist = pylag.EnergyLCList(lcfiles='*.lc')

~/anaconda3/lib/python3.9/site-packages/pylag/lightcurve.py in __init__(self, searchstr, lcfiles, enmin, enmax, lclist, **kwargs)
   1545             self.enmax = np.array(enmax)
   1546         else:
-> 1547             self.enmin, self.enmax, self.lclist = self.find_light_curves(searchstr, lcfiles, **kwargs)
   1548 
   1549         self.en = 0.5*(self.enmin + self.enmax)

~/anaconda3/lib/python3.9/site-packages/pylag/lightcurve.py in find_light_curves(searchstr, lcfiles, **kwargs)
   1596         if lcfiles is None:
   1597             lcfiles = sorted(glob.glob(searchstr))
-> 1598         enlist = list(set([re.search('(en[0-9]+\-[0-9]+)', lc).group(0) for lc in lcfiles]))
   1599 
   1600         obsid_list = list(set([re.search('(.*?)_(tbin[0-9]+)_(en[0-9]+\-[0-9]+)', lc).group(1) for lc in lcfiles]))

~/anaconda3/lib/python3.9/site-packages/pylag/lightcurve.py in <listcomp>(.0)
   1596         if lcfiles is None:
   1597             lcfiles = sorted(glob.glob(searchstr))
-> 1598         enlist = list(set([re.search('(en[0-9]+\-[0-9]+)', lc).group(0) for lc in lcfiles]))
   1599 
   1600         obsid_list = list(set([re.search('(.*?)_(tbin[0-9]+)_(en[0-9]+\-[0-9]+)', lc).group(1) for lc in lcfiles]))

AttributeError: 'NoneType' object has no attribute 'group'

Please let me know what is to be done.
Thanks
